# Generated by Django 3.1.3 on 2021-03-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('pregunta', models.TextField()),
            ],
            options={
                'verbose_name': 'La Pregunta',
                'verbose_name_plural': 'Persona Pregunta',
                'db_table': 'question',
                'ordering': ['pk'],
                'permissions': [['autorizar_question', 'Permite Autorizar Persona Pregunta']],
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
